#!/usr/bin/env python3

import argparse
import struct
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools"))

import version_config


TABLES = (
    ("Sequence", "gSequenceTable"),
    ("SoundFont", "gSoundFontTable"),
    ("SampleBank", "gSampleBankTable"),
)


def read_table(code, offset):
    num_entries, unk_medium_param, rom_addr = struct.unpack(">hhI", code[offset : offset + 8])
    entries = []

    for i in range(num_entries):
        entry_offset = offset + 0x10 + (i * 0x10)
        entries.append(struct.unpack(">IIbbhhh", code[entry_offset : entry_offset + 0x10]))

    return num_entries, unk_medium_param, rom_addr, entries


def emit_u8_array(out, name, data):
    out.append(f"ALIGNED(2) u8 {name}[] = {{")

    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        out.append("    " + ", ".join(f"0x{byte:02X}" for byte in chunk) + ",")

    out.append("};")
    out.append("")


def emit_table(out, tag, symbol, num_entries, unk_medium_param, rom_addr, entries):
    prefix = f"sPsp{tag}Table"
    struct_name = f"OotPsp{tag}Table"

    out.append(f"typedef struct {struct_name} {{")
    out.append("    AudioTableHeader header;")
    out.append(f"    AudioTableEntry entries[{num_entries}];")
    out.append(f"}} {struct_name};")
    out.append("")
    out.append(f"#pragma weak {symbol} = {prefix}")
    out.append("")
    out.append(f"NO_REORDER {struct_name} {prefix} = {{")
    out.append("    {")
    out.append(f"        {num_entries},")
    out.append(f"        {unk_medium_param},")
    out.append(f"        0x{rom_addr:08X},")
    out.append("        { 0, 0, 0, 0, 0, 0, 0, 0 },")
    out.append("    },")
    out.append("    {")

    for rom, size, medium, cache_policy, short1, short2, short3 in entries:
        out.append(
            "        { "
            f"0x{rom:08X}, 0x{size:08X}, {medium}, {cache_policy}, "
            f"0x{short1 & 0xFFFF:04X}, 0x{short2 & 0xFFFF:04X}, 0x{short3 & 0xFFFF:04X}"
            " },"
        )

    out.append("    },")
    out.append("};")
    out.append("")


def generate(version, output):
    config = version_config.load_version_config(version)
    baserom_dir = ROOT / "extracted" / version / "baserom"
    code = (baserom_dir / "code").read_bytes()
    code_vram = config.dmadata_segments["code"].vram

    table_data = {}
    for tag, symbol in TABLES:
        table_offset = config.variables[symbol] - code_vram
        table_data[symbol] = (tag, symbol, *read_table(code, table_offset))

    seq_font_start = config.variables["gSequenceFontTable"] - code_vram
    seq_table_start = config.variables["gSequenceTable"] - code_vram
    seq_font_table = bytearray(code[seq_font_start:seq_table_start])
    num_sequences = table_data["gSequenceTable"][2]

    # The table begins with u16 offsets and then continues as byte-sized font lists.
    # The N64 stores the offsets big-endian, but PSP reads them through a u16* cast.
    for i in range(num_sequences):
        entry_offset = i * 2
        value = struct.unpack(">H", seq_font_table[entry_offset : entry_offset + 2])[0]
        seq_font_table[entry_offset : entry_offset + 2] = struct.pack("<H", value)

    out = [
        "/* Generated by tools/psp_port_audio_tables.py. */",
        '#include "alignment.h"',
        '#include "attributes.h"',
        '#include "audio.h"',
        "",
    ]

    emit_u8_array(out, "gSequenceFontTable", seq_font_table)

    for tag, symbol in TABLES:
        emit_table(out, *table_data[symbol])

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(out))


def main():
    parser = argparse.ArgumentParser(description="Generate PSP raw-audio table definitions")
    parser.add_argument("version")
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    generate(args.version, args.output)


if __name__ == "__main__":
    main()
